version: '3'

services:
  function:
    build:
      context: .
      dockerfile: Dockerfile
    init: true
    volumes:
      - ../:/workspace:cached
    command: sleep infinity
    user: vscode

  azurite:
    image: "mcr.microsoft.com/azure-storage/azurite"
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
