# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy dotnet core project to Azure Function App

on:
  push:
    branches:
      - main
    paths:
      - 'ChatGPTLineBot/**'
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: ChatGPTLineBot/published
  CONFIGURATION: Release
  DOTNET_VERSION: 8.0.x
  WORKING_DIRECTORY: ChatGPTLineBot

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore "${{ env.WORKING_DIRECTORY }}"
        
      - name: Build
        run: dotnet build "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-restore
        
      - name: Publish
        run: dotnet publish "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}"

      - name: Publish Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: functionapp
          path: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.fa.outputs.webapp-url }}
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: functionapp

      - name: Az CLI Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Azure App Service Settings
        uses: Azure/appservice-settings@v1
        with:
          app-name: ${{ vars.AZURE_FUNCTION_APP_NAME }}
          slot-name: 'Production'
          app-settings-json: '[{"name":"AzureOpenAIApiKey","value":"${{ secrets.AZURE_OPENAI_APIKEY }}","slotSetting":false},{"name":"AzureOpenAIDeploymentName","value":"${{ vars.AZURE_OPENAI_DEPLOYMENT_NAME }}","slotSetting":false},{"name":"AzureOpenAIResourceName","value":"${{ vars.AZURE_OPENAI_RESOURCE_NAME }}","slotSetting":false},{"name":"LineAccessToken","value":"${{ secrets.LINE_ACCESS_TOKEN }}","slotSetting":false},{"name":"LineChannelSecret","value":"${{ secrets.LINE_CHANNEL_SECRET }}","slotSetting":false}]'

      - name: Azure Functions Configuration
        run: |
          az functionapp config appsettings set --settings FUNCTIONS_EXTENSION_VERSION=~4 --name ${{ vars.AZURE_FUNCTION_APP_NAME }} --resource-group ${{ vars.RESOURCE_GROUP_NAME }}
          az functionapp config set --name ${{ vars.AZURE_FUNCTION_APP_NAME }} --resource-group ${{ vars.RESOURCE_GROUP_NAME }} --linux-fx-version "DOTNET-ISOLATED|8.0"

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ vars.AZURE_FUNCTION_APP_NAME }}
          slot-name: 'Production'
          package: .

      - name: Az CLI Logout
        run: az logout
